### ISSUE TITLE
Update footer section css

### ISSUE THREAD

**Issue by sephlao** [wddm-122-alpha/wddm-122-alpha.github.io#17]
![footer](https://user-images.githubusercontent.com/11917969/75504151-ade28180-59a5-11ea-9a92-5e34c3718f1c.png)
Attached is the high fidelity wireframe for footer. Please follow styling accordingly.
- [x] Use Source Sans Pro as font
- [x]  Navigation text color #B7B7B7
- [ ] Remove circular border on social icons
- [x] Adjust spacing and font size on mobile to fit grid layout

**Comment by bijaybdrkarki** [comment]
removing circular border in social icon ....will not give color full hover effect as i have already created so how about we add that circular border into the figma.

**Comment by bijaybdrkarki** [comment]
also when i see footer section on mobile version there is no space for grid.....do u want me to decrease font size and implement grid or leave it for now
<img width="308" alt="Screen Shot 2020-02-28 at 03 33 20" src="https://user-images.githubusercontent.com/37946823/75524175-5fe87080-59db-11ea-8899-c72d5f8db572.png">

**Comment by bijaybdrkarki** [comment]
created footer as asked 
<img width="212" alt="Screen Shot 2020-02-28 at 21 21 18" src="https://user-images.githubusercontent.com/37946823/75599188-768cd700-5a70-11ea-94e3-13231634cdf8.png">
<img width="396" alt="Screen Shot 2020-02-28 at 21 21 33" src="https://user-images.githubusercontent.com/37946823/75599189-77256d80-5a70-11ea-8384-b342b8928fce.png">
<img width="688" alt="Screen Shot 2020-02-28 at 21 21 45" src="https://user-images.githubusercontent.com/37946823/75599190-77256d80-5a70-11ea-97dc-dd6596c0666d.png">
