### ISSUE TITLE
Add padding to header section and align navigation items to the right

### ISSUE THREAD

**Issue by sephlao** [wddm-122-alpha/wddm-122-alpha.github.io#24]
<img width="1274" alt="Screen Shot 2020-03-02 at 12 43 14 PM" src="https://user-images.githubusercontent.com/11917969/75702426-79134a80-5c83-11ea-9fc5-6788b592ac3a.png">
** note in this screenshot the navigation items are still centered. 

- [x] add padding to header section 1em top & bottom; 1.5em each sides
- [x] add min-height to header 3.75em
- [x] increase font size to 1.125em
- [x] decrease space of navigation items and search icon; only expand when clicked (showing input field)

**Comment by bijaybdrkarki** [comment]
work done as asked and created PR
